name: Compress Plugin
on:
  push:
  pull_request:
jobs:
  composer-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: composer install --ansi --no-progress --no-interaction --prefer-dist
      - run: mkdir output
      - uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./output/add-nocache.zip ./add-nocache
      - uses: actions/upload-artifact@master
        with:
          name: add-nocache
          path: output
